# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{secret.SONAR_TOKEN}}
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: >
        ./mvnw clean verify
        sonar:sonar
        -Pcoverage
        -Dsonar.host.url=https://sonarcloud.io
        -Dsonar.organization=forestik
        -Dsonar.projectKey=forestik
        -Dsonar.scm.disabled=True
